### ISSUE TITLE
Step-by-step instructions

### ISSUE THREAD

**Issue by chiefymuc** [plaetzchen/F1-WLED-Live#1]
This is such a cool idea!

May I ask to get a step-by-step instruction? I'm struggling to set up f1-live-data to begin with.

I'm trying it on the Ubuntu on Windows 11 subsystem. Maybe it is not suitable?

**Comment by plaetzchen** [comment]
Wow, me first issue, thanks @chiefymuc !

So it should be possible and the easiest is to use Docker Desktop in that case for the f1-live-data part. It should work pretty much out of the box and you have the InfluxDB, Grafana and Python ingestion needed. Then you can already watch the action as it happens.

To the use the WLED script you can run it on the same machine and just point the InfluxDB to "influxdb" and the token used in F1-live-data can be found in the src/dataimporter/importer.py script.

With the season kicking off I will also try to make it easier as well.

**Comment by plaetzchen** [comment]
I also added a fork of the F1 Live Data repo to update the Message Handler for 2024

**Comment by chiefymuc** [comment]
Ok so I managed to install Docker Desktop and run the f1-live-data. I can see on my browser the InfluxDB and the data.

I went in InfluxDB to the settings and created an API Key (I assume this is the token needed for your python script?).

Now when I run the python script I get this error:

```
python .\f1-wled-live.py
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 12, in <module>
    INFLUX_TOKEN = os.environ["INFLUXDB_TOKEN"]
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'INFLUXDB_TOKEN'
```

Of course here I put the API KEY string.. but doesn't matter what I put here.

This ist the config:

```
## Configure Influx DB
INFLUX_TOKEN = os.environ["INFLUXDB_TOKEN"]
INFLUX_ORG = "Call a Nerd"
INFLUX_URL = "localhost:3000"
```

**Comment by plaetzchen** [comment]
@chiefymuc OK so you need to do two things:
1: Update the INFLUX_ORG to the one in your InfluxDB, the name or ID, you can find them in the left hand menu (it should say your name and org name) and then under "About". 
2: Replace the os.environ with the token in simple quotes "", this should work (environment variables are not really a thing in windows I think)

**Comment by chiefymuc** [comment]
OK getting closer!

Next issues:

I still have "sock = None"
I do not understand what is meant by "The global variable for the WLED socket to be able to close it"

```
PS C:\Users\david\docker\F1-WLED-Live> python .\f1-wled-live.py
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 192, in <module>
    main()
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 186, in main
    frame, seconds_per_segment = getDataFromDB()
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 106, in getDataFromDB
    tables = query_api.query(query, org="Call a Nerd")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\client\query_api.py", line 203, in query
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 285, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 311, in post_query_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 173, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 388, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 311, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 186, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 365, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 237, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
Closing socket
Exception ignored in atexit callback: <function closeSock at 0x000001ADEBDF8CC0>
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 170, in closeSock
    sock.close()
    ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by chiefymuc** [comment]
It seems that line 106 has hardcoded:
`tables = query_api.query(query, org="Call a Nerd")`

**Comment by plaetzchen** [comment]
Fixed line 106 but that's not your problem. The Influx URL is wrong. The port needs to bei 8086 and host influxdb so please try "influxdb:8086"

**Comment by plaetzchen** [comment]
Oh and the Sock is just an error since there is no socket opened yet. Could wrap it in a try-catch but that's not your problem

**Comment by chiefymuc** [comment]
Ok I fixed that.

Now I realized, I mixed up Grafana and InfluxDB token.

How do I get a InfluxDB token?

I can open http://localhost:8086/signin but then I do not know what the password is. I guess it got auto-setup by the f1-live-data script?

Sorry that I need so much basic help.

**Comment by plaetzchen** [comment]
No worries at all, happy to help.

The user is admin and the password is password

The token to use is also in the script, it's wwPE9MycN2RzYX2ngYuap-Ri5pt5YOrxcVqN_u46SOs6CBj8SGKzxBHJpLnLfPrXLJZFLpEtzwoJR3Ik_8M2NQ==

**Comment by chiefymuc** [comment]
unfortunately that also does not work :(

I could login and also make another API Token

```
PS C:\Users\david\docker\F1-WLED-Live> python .\f1-wled-live.py
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 192, in <module>
    main()
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 186, in main
    frame, seconds_per_segment = getDataFromDB()
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 106, in getDataFromDB
    tables = query_api.query(query, org=INFLUX_ORG)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\client\query_api.py", line 203, in query
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 285, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 311, in post_query_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 173, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 388, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 311, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 186, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 365, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 237, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
Closing socket
Exception ignored in atexit callback: <function closeSock at 0x000001A85C1E8D60>
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 170, in closeSock
    sock.close()
    ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
PS C:\Users\david\docker\F1-WLED-Live> python .\f1-wled-live.py
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 192, in <module>
    main()
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 186, in main
    frame, seconds_per_segment = getDataFromDB()
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 106, in getDataFromDB
    tables = query_api.query(query, org=INFLUX_ORG)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\client\query_api.py", line 203, in query
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 285, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 311, in post_query_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 173, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 388, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 311, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 186, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 365, in urlopen
    conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 237, in connection_from_host
    raise LocationValueError("No host specified.")
urllib3.exceptions.LocationValueError: No host specified.
Closing socket
Exception ignored in atexit callback: <function closeSock at 0x0000015714748D60>
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 170, in closeSock
    sock.close()
    ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by plaetzchen** [comment]
OK, can you please share line 11 to 18 in your script?

**Comment by chiefymuc** [comment]
```
## Configure Influx DB
INFLUX_TOKEN = "aUg8MbXx_Kb8Mu_kHPsLFNstZe-w2no7qjV64hkO_091Xuw67qBRwjxv_hi4suUppYwThgWOsep8i-avZTMMlg=="
INFLUX_ORG = "f1"
INFLUX_URL = "influxdb:8086"

WLED_IP = "192.168.178.105"
WLED_PORT = 21324
WLED_LED_COUNT = 124

## The global counter for the animation 
current_frame = 0

## The global variable for the WLED socket to be able to close it
sock = None

```

**Comment by chiefymuc** [comment]
In InfluxDB I made a new all-access API Token called "f1"

**Comment by plaetzchen** [comment]
Please change:

INFLUX_URL = "influxdb:8086"

to

INFLUX_URL = "http://influxdb:8086"

Sorry I had that wrong earlier

**Comment by chiefymuc** [comment]
Does not seem to make a difference:

```
PS C:\Users\david\docker\F1-WLED-Live> python .\f1-wled-live.py
Traceback (most recent call last):
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 192, in <module>
    main()
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 186, in main
    frame, seconds_per_segment = getDataFromDB()
                                 ^^^^^^^^^^^^^^^
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 106, in getDataFromDB
    tables = query_api.query(query, org=INFLUX_ORG)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\client\query_api.py", line 203, in query
    response = self._query_api.post_query(org=org, query=self._create_query(query, self.default_dialect, params),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 285, in post_query
    (data) = self.post_query_with_http_info(**kwargs)  # noqa: E501
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\service\query_service.py", line 311, in post_query_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 343, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 173, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\api_client.py", line 388, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 311, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\influxdb_client\_sync\rest.py", line 186, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000291EB07BA10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
Closing socket
Exception ignored in atexit callback: <function closeSock at 0x00000291EB278D60>
Traceback (most recent call last):
  File "C:\Users\david\docker\F1-WLED-Live\f1-wled-live.py", line 170, in closeSock
    sock.close()
    ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by plaetzchen** [comment]
It can not connect, can you try:

INFLUX_URL = "http://localhost:8086"

**Comment by plaetzchen** [comment]
Also, please change INFLUX_ORG to c6d6c0228d6fd3ea

**Comment by chiefymuc** [comment]
It works! Changing the org was not necessary!

This is super cool!,

Thanks so much for the help

**Comment by plaetzchen** [comment]
Great! I will add some points to the README later on
